#!/usr/bin/env bash
set -euo pipefail

if [[ "${RENDER:-}" == "true" ]]; then
  export CHAPI_LOW_MEMORY_MODE="${CHAPI_LOW_MEMORY_MODE:-1}"
  export CHAPI_PERSISTENT_WORKER="${CHAPI_PERSISTENT_WORKER:-0}"
  export CHAPI_WORKER_WARMUP_AT_STARTUP="${CHAPI_WORKER_WARMUP_AT_STARTUP:-0}"
  export CHAPI_SPLIT_CHAIN_BATCH_LIMIT="${CHAPI_SPLIT_CHAIN_BATCH_LIMIT:-1}"
  export CHAPI_MESH_CACHE_MAX_ENTRIES="${CHAPI_MESH_CACHE_MAX_ENTRIES:-1}"
  export CHAPI_MESH_CACHE_MAX_BYTES="${CHAPI_MESH_CACHE_MAX_BYTES:-0}"
  export STRUCTURE_TEXT_CACHE_MAX_ENTRIES="${STRUCTURE_TEXT_CACHE_MAX_ENTRIES:-1}"
fi

exec uvicorn api.main:app --host 0.0.0.0 --port "${PORT:-8000}"
